# Site
name: 'Ремонт Менталки'
description: 'Всім треба мати змогу піклуватися про свої емоції. Онлайн консультація психолога @PSY_aibot'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#baseurl: '/remontmentalky'
baseurl: ''
disqus: 'remontmentalky'
email: 'remontmentalky@txtHiveHub.com'
mailchimp-list: 'https://t.me/PSY_aibot'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
#    sal:
#      name:           Sal
#      site:           https://www.wowthemes.net
#      avatar:         /assets/images/avatar1.jpg
#      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
#      email:          wowthemesnet@gmail.com
#      twitter:        https://twitter.com/wowthemesnet

    psy:
      name:           Вікторія
      site:           https://t.me/PSY_aibot
      avatar:         /assets/images/avatar2.jpg
      bio:            "Психологиня, блогерка."
      email:          psy_ai@txthivehub.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: psy
      avatar: /assets/images/avatar2.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 15


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
